# Generated by Django 3.2.5 on 2021-12-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0003_rename_tweet_csvtweets_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtweets',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='sentiment_api.csv'),
        ),
    ]
