# Generated by Django 3.2.5 on 2021-12-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0008_alter_csvtweets_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtweets',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_tweets', related_query_name='csv_tweets', to='sentiment_api.csv'),
        ),
    ]
