# Generated by Django 3.2.5 on 2021-12-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_api', '0013_alter_csvtweets_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvtweets',
            name='csv',
        ),
        migrations.AddField(
            model_name='csv',
            name='tweets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentiment_api.csvtweets'),
        ),
    ]
