# Generated by Django 3.2.5 on 2021-12-31 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(max_length=200, upload_to='csvs')),
                ('sentiment', models.CharField(max_length=10, null=True)),
                ('polarity', models.FloatField(null=True)),
                ('activated', models.BooleanField(default=False)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_tweet', models.CharField(max_length=280)),
                ('sentiment', models.CharField(max_length=10)),
                ('polarity', models.FloatField(null=True)),
                ('MA_window', models.IntegerField(default=10)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('polarity', models.FloatField(null=True)),
                ('sentiment', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CsvTweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('tweetnum', models.IntegerField(null=True)),
                ('csv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.csv')),
            ],
        ),
    ]
