# Generated by Django 3.2.5 on 2021-12-05 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
