# Generated by Django 3.2.5 on 2021-12-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetweet',
            name='sentiment',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
