# Generated by Django 3.2.5 on 2021-12-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211207_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(max_length=200, upload_to='csv')),
                ('tweets', models.CharField(max_length=280)),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
