# Generated by Django 3.2.5 on 2021-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweets', models.CharField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='csv',
            name='tweets',
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(max_length=200, upload_to='csvs'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
