# Generated by Django 3.2.5 on 2021-12-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_csvtweets_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvtweets',
            name='created',
        ),
    ]
