# Generated by Django 3.2.5 on 2021-12-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_csvtweets_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtweets',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_tweets', to='home.csv'),
        ),
    ]
