# Generated by Django 3.2.5 on 2021-12-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_csvtweets_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvtweets',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.csv'),
        ),
    ]
