# Generated by Django 3.2.5 on 2021-12-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211231_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='tweets',
        ),
        migrations.AddField(
            model_name='csvtweets',
            name='csv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_tweets', to='home.csv'),
        ),
    ]
