# Generated by Django 3.2.5 on 2022-01-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_csvtweets_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='activated',
        ),
    ]
